### PR TITLE
fix: re-enable static typing

### LINKED ISSUE #1195: v31 gave all APIs 'any' type
All APIs seem to have the 'any' type after upgrading googleapis to v31.0.2. For example:
```
import { google } from 'googleapis';
const gmail = google.gmail({ version: 'v1', params: { userId: 'me' } });
```
`gmail` has type any. This prevents the type definitions for gmail from being used.

After investigating I believe the cause of this issue is that with v31 in my `node_modules/googleapis/build/src/apis/index.d.ts` file I have:
```/*! THIS FILE IS AUTO-GENERATED */
export interface APIList {
    [index: string]: {
        [index: string]: any;
    };
}
export declare const APIS: APIList;
export declare class GeneratedAPIs {
    abusiveexperiencereport: any;
    acceleratedmobilepageurl: any;
    adexchangebuyer: any;
    adexchangebuyer2: any;
    adexchangeseller: any;
    adexperiencereport: any;
    admin: any;
    adsense: any;
    adsensehost: any;
    analytics: any;
    analyticsreporting: any;
    androiddeviceprovisioning: any;
    androidenterprise: any;
    androidmanagement: any;
    androidpublisher: any;
    appengine: any;
    appsactivity: any;
    appstate: any;
    bigquery: any;
    bigquerydatatransfer: any;
    blogger: any;
    books: any;
    calendar: any;
    chat: any;
    civicinfo: any;
    classroom: any;
    cloudbilling: any;
    cloudbuild: any;
    clouddebugger: any;
    clouderrorreporting: any;
    cloudfunctions: any;
    cloudiot: any;
    cloudkms: any;
    cloudresourcemanager: any;
    cloudshell: any;
    cloudtasks: any;
    cloudtrace: any;
    composer: any;
    compute: any;
    container: any;
    content: any;
    customsearch: any;
    dataflow: any;
    dataproc: any;
    datastore: any;
    deploymentmanager: any;
    dfareporting: any;
    dialogflow: any;
    digitalassetlinks: any;
    discovery: any;
    dlp: any;
    dns: any;
    doubleclickbidmanager: any;
    doubleclicksearch: any;
    drive: any;
    firebasedynamiclinks: any;
    firebaserules: any;
    firestore: any;
    fitness: any;
    fusiontables: any;
    games: any;
    gamesConfiguration: any;
    gamesManagement: any;
    genomics: any;
    gmail: any;
    groupsmigration: any;
    groupssettings: any;
    iam: any;
    identitytoolkit: any;
    jobs: any;
    kgsearch: any;
    language: any;
    licensing: any;
    logging: any;
    manufacturers: any;
    mirror: any;
    ml: any;
    monitoring: any;
    oauth2: any;
    oslogin: any;
    pagespeedonline: any;
    partners: any;
    people: any;
    photoslibrary: any;
    playcustomapp: any;
    plus: any;
    plusDomains: any;
    poly: any;
    proximitybeacon: any;
    pubsub: any;
    redis: any;
    replicapool: any;
    replicapoolupdater: any;
    reseller: any;
    resourceviews: any;
    runtimeconfig: any;
    safebrowsing: any;
    script: any;
    searchconsole: any;
    servicebroker: any;
    serviceconsumermanagement: any;
    servicecontrol: any;
    servicemanagement: any;
    serviceusage: any;
    serviceuser: any;
    sheets: any;
    siteVerification: any;
    slides: any;
    sourcerepo: any;
    spanner: any;
    spectrum: any;
    speech: any;
    sqladmin: any;
    storage: any;
    storagetransfer: any;
    streetviewpublish: any;
    surveys: any;
    tagmanager: any;
    tasks: any;
    testing: any;
    texttospeech: any;
    toolresults: any;
    tpu: any;
    translate: any;
    urlshortener: any;
    vault: any;
    videointelligence: any;
    vision: any;
    webfonts: any;
    webmasters: any;
    websecurityscanner: any;
    youtube: any;
    youtubeAnalytics: any;
    youtubereporting: any;
}

```

For now I will continue using v30 as a workaround.

### PR DESCRIPTION
**Pull request by JustinBeckwith**
I broke this while generating individual index files.  Turns out, `fn.bind(this)` doesn't preserve the function type 🤷‍♂️ 

Fixes #1195

### CODE REVIEW

File: src/apis/logging/v2.ts [hunk 1]
```diff
@@ -623,9 +623,9 @@ export namespace logging_v2 {
      * Required. An advanced logs filter that matches the log entries to be
      * excluded. By using the sample function, you can exclude less than 100% of
      * the matching log entries. For example, the following filter matches 99%
-     * of low-severity log entries from load balancers:
-     * &quot;resource.type=http_load_balancer severity&lt;ERROR sample(insertId,
-     * 0.99)&quot;
+     * of low-severity log entries from load
+     * balancers:&quot;resource.type=http_load_balancer severity&lt;ERROR
```
Comment (alexander-fenster) [inline src/apis/logging/v2.ts]: why this formatting change? it looked better with the new line.

Comment (JustinBeckwith) [reply src/apis/logging/v2.ts]: 🤷‍♂️ I follow the rules of my `clang-format` overlords
